### PR TITLE
Add possibility to explicit the AWS profile you want to use

### PR DESCRIPTION
**Pull request by luanmuniz**
That way if i have more than one profile in my machine i can specify which one i want to use

The way the profile is set is documented in
http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html

If you want to change the `args` name from `aws-profile` to something else, or if you want to make any changes let me know.

### CODE REVIEW

**Comment by stojanovic** [comment]
Can you add the docs, actually just the option in README?
Also, I think we should use `--profile`.

Thanks

**Comment by luanmuniz** [comment]
@stojanovic Sure! What shortcut should i use? is `-a` ok? `-p`and `-c` are already being used :(

**Comment by stojanovic** [comment]
Hm, no need for the shortcut for now, it will be slightly different in v2 anyway. But if you want pick anything that you think it's good enough :)

**Comment by luanmuniz** [comment]
Done! Cc @stojanovic

**Comment by stojanovic** [comment]
Thanks, I'll push it on NPM tomorrow morning :)

**Pull request merged**
