### PR TITLE
Added the no clipboard option

### PR DESCRIPTION
**Pull request by Jack12816**
**- What is it good for**

Looks like on CI conditions the clipboard copying fails. With the new option you can
configure shottyjs to skip the clipboard handling. With this option the CI build failed
no more.

**- What I did**

* Updated the readme
* Added `--noclipboard` option to disable clipboardy

**- What I did not**

Due to the tight coupling of the `bin/scotty` binary to the `lib/scotty` module was
not able to test the new option. If you can provide me a clever solution how to
test this I will do so. :)

**- A picture of a cute animal (not mandatory but encouraged)**

images

### CODE REVIEW

**Comment by Jack12816** [comment]
@stojanovic You're the best :heart:

**Comment by simalexan** [comment]
omg guys! :D get a room!

**Comment by stojanovic** [comment]
Keep 'em coming :)
v1.8.0 is going to NPM in a second

**Comment by Jack12816** [comment]
Hey @stojanovic :) looks like you forgot to release the 1.8.0 on npm. Could you publish it? :)

**Comment by stojanovic** [comment]
@Jack12816 oops, done

**Pull request merged**
